[[constraint]]
  name = "github.com/SKF/go-eventsource"
  version = "1.3.1"

[[constraint]]
  name = "github.com/SKF/go-utility"
  version = "1.4.1"

[[constraint]]
  name = "github.com/SKF/proto"
  version = "1.25.7-go"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.12.2"

[prune]
  go-tests = true
  unused-packages = true
